#name: smart_tracker
#description: "A new Flutter project."
#publish_to: 'none'  # Remove this line if you wish to publish to pub.dev
#
#version: 1.0.0+1
#
#environment:
#  sdk: ">=3.6.0 <4.0.0"  # Ensure SDK compatibility
#
#dependencies:
#  flutter:
#    sdk: flutter
#
#  # Firebase packages (Updated to latest stable versions)
#  firebase_core: ^2.27.0
#  firebase_auth: ^4.17.4
#  cloud_firestore: ^4.15.4
#  firebase_messaging: ^14.7.20
#
#  # Uncomment these if you need notifications, permissions, and barcode scanning
#  #  flutter_local_notifications: ^16.3.2
#  #  timezone: ^0.9.0
#  #  permission_handler: ^11.3.1
#  #  workmanager: ^0.5.1
#  #  intl: ^0.20.2
#
#  # Google ML Kit for OCR
#  google_ml_kit: ^0.19.0
#  image_picker: ^1.1.2
#
#  # UI and Utility packages
#  cupertino_icons: ^1.0.8
##  flutter_barcode_scanner: ^2.0.0 # Barcode scanner package
##  http: ^1.3.0             # HTTP client for API calls
#
#dev_dependencies:
#  flutter_test:
#    sdk: flutter
#
#  flutter_lints: ^3.0.0  # Latest linting package
#
#flutter:
#  uses-material-design: true



name: smart_tracker
description: "A new Flutter project."
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"  # Ensure SDK compatibility

dependencies:
  flutter:
    sdk: flutter

  # Firebase packages (Updated to latest stable versions)
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  firebase_messaging: ^15.2.1
  google_ml_kit: ^0.19.0
  image_picker: ^1.1.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.2
  intl: ^0.18.0
  # UI and Utility packages
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

